version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk AS
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet test --no-build AspWebapi.Test